In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Student": ["A", "B", "C", "D", "E",
                "F", "G", "H", "I", "J"],

    "Marks": [50, 55, 60, 62, 65,
              68, 70, 72, 75, 150]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
print("Original Dataset:")
display(df)

Original Dataset:

  Student  Marks
0       A     50
1       B     55
2       C     60
3       D     62
4       E     65
5       F     68
6       G     70
7       H     72
8       I     75
9       J    150

In [5]:
Q1 = df["Marks"].quantile(0.25)

print(Q1)

60.5

In [6]:
Q3 = df["Marks"].quantile(0.75)

print(Q3)

71.5

In [7]:
IQR = Q3 - Q1

print(IQR)

11.0

In [8]:
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print(lower_limit)

print(upper_limit)

44.0
88.0

In [9]:
print("\nQ1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

Q1: 60.5
Q3: 71.5
IQR: 11.0
Lower Limit: 44.0
Upper Limit: 88.0

In [10]:
outliers = df[
    (df["Marks"] < lower_limit) |
    (df["Marks"] > upper_limit)
]

In [11]:
print("\nOutliers using IQR:")
print(outliers)

Outliers using IQR:
  Student  Marks
9       J    150

In [12]:
df["Marks_Treated"] = np.where(
    df["Marks"] > upper_limit,
    upper_limit,
    np.where(
        df["Marks"] < lower_limit,
        lower_limit,
        df["Marks"]
    )
)

In [13]:
df_capped = df.copy()

In [14]:
df_capped["Marks"] = df_capped["Marks"].clip(
    lower=lower_limit,
    upper=upper_limit
)

In [21]:
print("\nAfter Capping:")
display(df_capped)

After Capping:

  Student  Marks  Marks_Treated
0       A     50           50.0
1       B     55           55.0
2       C     60           60.0
3       D     62           62.0
4       E     65           65.0
5       F     68           68.0
6       G     70           70.0
7       H     72           72.0
8       I     75           75.0
9       J     88           88.0

In [22]:
print("\nDataset After Outlier Treatment:")
display(df)

Dataset After Outlier Treatment:

  Student  Marks  Marks_Treated
0       A     50           50.0
1       B     55           55.0
2       C     60           60.0
3       D     62           62.0
4       E     65           65.0
5       F     68           68.0
6       G     70           70.0
7       H     72           72.0
8       I     75           75.0
9       J    150           88.0