In [1]:
import pandas as pd

import numpy as np

from scipy.stats import zscore

In [2]:
data = {

    "Student": ["A", "B", "C", "D", "E",

                "F", "G", "H", "I", "J",

                "K", "L", "M", "N", "O",

                "P", "Q", "R", "S", "T"],

    "Marks": [50, 52, 54, 55, 56,

              58, 60, 61, 62, 63,

              64, 65, 66, 68, 70,

              71, 72, 73, 75, 200]

}

In [3]:
df = pd.DataFrame(data)

In [5]:
print("Original Dataset:")

display(df)

Original Dataset:

   Student  Marks
0        A     50
1        B     52
2        C     54
3        D     55
4        E     56
5        F     58
6        G     60
7        H     61
8        I     62
9        J     63
10       K     64
11       L     65
12       M     66
13       N     68
14       O     70
15       P     71
16       Q     72
17       R     73
18       S     75
19       T    200

In [6]:
df["Z_Score"] = zscore(df["Marks"])

In [8]:
print("\nZ-Scores:")

display(df)

Z-Scores:

   Student  Marks   Z_Score
0        A     50 -0.643187
1        B     52 -0.578054
2        C     54 -0.512921
3        D     55 -0.480355
4        E     56 -0.447788
5        F     58 -0.382655
6        G     60 -0.317523
7        H     61 -0.284956
8        I     62 -0.252390
9        J     63 -0.219823
10       K     64 -0.187257
11       L     65 -0.154691
12       M     66 -0.122124
13       N     68 -0.056991
14       O     70  0.008142
15       P     71  0.040708
16       Q     72  0.073274
17       R     73  0.105841
18       S     75  0.170974
19       T    200  4.241777

In [9]:
outliers = df[abs(df["Z_Score"]) > 3]

In [12]:
print("\nOutliers using Z-score:")

display(outliers)

Outliers using Z-score:

   Student  Marks   Z_Score
19       T    200  4.241777

In [13]:
mean = df["Marks"].mean()

In [14]:
std = df["Marks"].std(ddof=0)

In [15]:
lower_limit = mean - (3 * std)

upper_limit = mean + (3 * std)

In [16]:
print("\nMean:", mean)

print("Standard Deviation:", std)

print("Lower Limit:", lower_limit)

print("Upper Limit:", upper_limit)

Mean: 69.75
Standard Deviation: 30.70647325890748
Lower Limit: -22.369419776722438
Upper Limit: 161.86941977672245

In [17]:
df["Marks_Treated"] = df["Marks"].clip(

    lower=lower_limit,

    upper=upper_limit

)

In [18]:
print("\nAfter Z-score Capping:")

display(df)

After Z-score Capping:

   Student  Marks   Z_Score  Marks_Treated
0        A     50 -0.643187       50.00000
1        B     52 -0.578054       52.00000
2        C     54 -0.512921       54.00000
3        D     55 -0.480355       55.00000
4        E     56 -0.447788       56.00000
5        F     58 -0.382655       58.00000
6        G     60 -0.317523       60.00000
7        H     61 -0.284956       61.00000
8        I     62 -0.252390       62.00000
9        J     63 -0.219823       63.00000
10       K     64 -0.187257       64.00000
11       L     65 -0.154691       65.00000
12       M     66 -0.122124       66.00000
13       N     68 -0.056991       68.00000
14       O     70  0.008142       70.00000
15       P     71  0.040708       71.00000
16       Q     72  0.073274       72.00000
17       R     73  0.105841       73.00000
18       S     75  0.170974       75.00000
19       T    200  4.241777      161.86942