In [1]:
import pandas as pd

In [3]:
# 1. Load the dataset

df = pd.read_csv("indian_stock_market.csv")

In [4]:
# 2. Display the original dataset

print("ORIGINAL DATASET")
display(df)

ORIGINAL DATASET

,Company,Current_Price_INR,PE_Ratio,Market_Cap_Crore,Quarterly_Profit_Growth_Percent,Quarterly_Sales_Growth_Percent,ROCE_Percent,Collection_Date
0,20 Microns,200.08,10.52,706.01,14.99,14.80,17.43,2026-06-26
1,21st Cent. Mgmt.,33.20,NaN,34.86,-19.06,-27.89,-57.00,2026-06-26
2,360 ONE,1085.40,36.30,44141.59,15.68,35.91,12.13,2026-06-26
3,3B Blackbio,1159.70,16.99,995.33,13.81,57.47,25.48,2026-06-26
4,3B Films,16.58,22.32,41.07,36.76,-11.85,4.83,2026-06-26
...,...,...,...,...,...,...,...,...
5253,ZR2 Bioenergy,106.10,168.90,168.90,81.82,NaN,0.70,2026-06-26
5254,Zuari Agro Chem.,230.98,3.27,971.46,-212.74,-80.32,16.38,2026-06-26
5255,Zuari Industries,260.65,6.69,776.25,-56.79,4.15,5.45,2026-06-26
5256,Zydus Lifesci.,1101.40,20.43,110826.61,21.92,16.22,21.15,2026-06-26
5257,Zydus Wellness,518.10,71.02,16483.91,-5.76,62.60,4.96,2026-06-26

In [5]:
# 3. Display the first 5 records

print("FIRST 5 RECORDS")
display(df.head())

FIRST 5 RECORDS

,Company,Current_Price_INR,PE_Ratio,Market_Cap_Crore,Quarterly_Profit_Growth_Percent,Quarterly_Sales_Growth_Percent,ROCE_Percent,Collection_Date
0,20 Microns,200.08,10.52,706.01,14.99,14.80,17.43,2026-06-26
1,21st Cent. Mgmt.,33.20,NaN,34.86,-19.06,-27.89,-57.00,2026-06-26
2,360 ONE,1085.40,36.30,44141.59,15.68,35.91,12.13,2026-06-26
3,3B Blackbio,1159.70,16.99,995.33,13.81,57.47,25.48,2026-06-26
4,3B Films,16.58,22.32,41.07,36.76,-11.85,4.83,2026-06-26

In [6]:
# 4. Display the last 5 records

print("LAST 5 RECORDS")
display(df.tail())

LAST 5 RECORDS

,Company,Current_Price_INR,PE_Ratio,Market_Cap_Crore,Quarterly_Profit_Growth_Percent,Quarterly_Sales_Growth_Percent,ROCE_Percent,Collection_Date
5253,ZR2 Bioenergy,106.10,168.90,168.90,81.82,NaN,0.70,2026-06-26
5254,Zuari Agro Chem.,230.98,3.27,971.46,-212.74,-80.32,16.38,2026-06-26
5255,Zuari Industries,260.65,6.69,776.25,-56.79,4.15,5.45,2026-06-26
5256,Zydus Lifesci.,1101.40,20.43,110826.61,21.92,16.22,21.15,2026-06-26
5257,Zydus Wellness,518.10,71.02,16483.91,-5.76,62.60,4.96,2026-06-26

In [7]:
# 5. Display the number of rows and columns

print("DATASET SHAPE")
print(df.shape)

DATASET SHAPE
(5258, 8)

In [8]:
# 6. Display column names

print("COLUMN NAMES")
print(df.columns)

COLUMN NAMES
Index(['Company', 'Current_Price_INR', 'PE_Ratio', 'Market_Cap_Crore',
       'Quarterly_Profit_Growth_Percent', 'Quarterly_Sales_Growth_Percent',
       'ROCE_Percent', 'Collection_Date'],
      dtype='object')

In [9]:
# 7. Display data types

print("DATA TYPES")
print(df.dtypes)

DATA TYPES
Company                             object
Current_Price_INR                  float64
PE_Ratio                           float64
Market_Cap_Crore                   float64
Quarterly_Profit_Growth_Percent    float64
Quarterly_Sales_Growth_Percent     float64
ROCE_Percent                       float64
Collection_Date                     object
dtype: object

In [10]:
# 8. TOTAL DUPLICATE RECORDS

print("TOTAL DUPLICATE RECORDS")
print(df.duplicated().sum())

TOTAL DUPLICATE RECORDS
0

In [19]:
# 9. MISSING VALUES

print("MISSING VALUES")
print("-"*40)
print(df.isnull().sum())

MISSING VALUES
----------------------------------------
Company                               0
Current_Price_INR                    20
PE_Ratio                           1027
Market_Cap_Crore                      0
Quarterly_Profit_Growth_Percent     162
Quarterly_Sales_Growth_Percent      442
ROCE_Percent                        140
Collection_Date                       0
dtype: int64

In [20]:
# 10. ROWS CONTAINING MISSING VALUES

print("ROWS CONTAINING MISSING VALUES")
display(df[df.isnull().any(axis=1)])

ROWS CONTAINING MISSING VALUES

,Company,Current_Price_INR,PE_Ratio,Market_Cap_Crore,Quarterly_Profit_Growth_Percent,Quarterly_Sales_Growth_Percent,ROCE_Percent,Collection_Date
1,21st Cent. Mgmt.,33.20,NaN,34.86,-19.06,-27.89,-57.00,2026-06-26
10,63 Moons Tech.,669.50,NaN,3084.96,-138.76,881.22,-3.71,2026-06-26
16,A B M Internatl.,40.74,NaN,38.33,196.57,-18.68,-8.50,2026-06-26
17,A B Real Estate,1346.70,NaN,15042.06,-509.00,-79.07,-4.26,2026-06-26
19,A F Enterprises,1.69,NaN,5.65,6.67,370.00,-2.24,2026-06-26
...,...,...,...,...,...,...,...,...
5241,Zenith Steel,5.59,25.33,79.53,-96.30,-54.51,NaN,2026-06-26
5243,Zenotech Lab.,45.75,NaN,279.21,-347.58,-18.47,4.59,2026-06-26
5248,Zodiac Cloth. Co,83.28,NaN,228.67,-65.72,-6.90,-8.03,2026-06-26
5252,Zota Health Care,1389.50,NaN,4812.20,31.12,67.76,-8.47,2026-06-26
5253,ZR2 Bioenergy,106.10,168.90,168.90,81.82,NaN,0.70,2026-06-26